### ISSUE TITLE
Microsoft authenticate failed: Fail to extract PPFT or urlPost

### ISSUE THREAD

**Issue by twnku** [MCCTeam/Minecraft-Console-Client#1771]
Sometimes when my microsoft account disconnected and trying to relog or just run them for the first time, it will shows "Microsoft authenticate failed: Fail to extract PPFT or urlPost", especially when i tried to run multiple accounts (microsoft accounts) at the same time. it works fine with mojang account.

```
Console Client for MC 1.4.6 to 1.17.1 - v1.17.1 - By ORelio & Contributors
AppVeyor build 523, built on Wed 08/25/2021 from commit 41b0325
[MCC] [Settings] Loading Settings from C:\[Redacted]\MinecraftClient.ini
Resolving [Redacted]...
07:32:32 [MCC] [Translations] No translation file found for en. (Looked 'C:\[Redacted]\lang\mcc\en.ini'
07:32:32 [MCC] [Translations] No translation file found for system language (en). (Looked 'C:\[Redacted]\lang\mcc\en.ini'
07:32:32 Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]
Connecting to Microsoft...
< GET /oauth20_authorize.srf?client_id=[Redacted]&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en HTTP/1.0
< Host: login.live.com
< User-Agent: Mozilla/5.0 (XboxReplay; XboxLiveAuth/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
< Accept: */*
< Connection: close
<
<
07:33:02 Microsoft authenticate failed: Fail to extract PPFT or urlPost
07:33:02    at MinecraftClient.Protocol.XboxLive.PreAuth()
   at MinecraftClient.Protocol.ProtocolHandler.MicrosoftMCCLogin(String email, String password, SessionToken& session)
Minecraft Login failed :Incorrect password, blacklisted IP or too many logins.
07:33:02 [MCC] [AutoRelog] Launching with 2147483647 reconnection attempts
07:33:02 [MCC] [AutoRelog] Initializing without a kick message file
07:33:02 [MCC] [AutoRelog] Got disconnected with message: Minecraft Login failed :Incorrect password, blacklisted IP or too many logins.
07:33:02 [MCC] [AutoRelog] Ignoring kick message, reconnecting anyway.
07:33:02 [MCC] [AutoRelog] Waiting 60 seconds before reconnecting...
```

**Comment by ReinforceZwei** [comment]
I've tried signing in on my machine and it works fine. Maybe your IP address was blacklisted by Microsoft?

Or you may open the sign in page manually and see if you can sign in with it.
https://login.live.com/oauth20_authorize.srf?client_id=000000004C12AE6F&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en

**Comment by tunkusalim** [comment]
I can sign in manually to microsoft/outlook so it seems my ip isnt blacklisted, and my other account is able to sign in too.

```
Or you may open the sign in page manually and see if you can sign in with it.
https://login.live.com/oauth20_authorize.srf?client_id=000000004C12AE6F&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en
```
i opened it on my browser and only showing a blank page, is it normal?

not sure what happened, probably my connection is lagging because i run so many clients at once?

**Comment by ReinforceZwei** [comment]
Normally you should see the sign-in page like this:
![image](https://user-images.githubusercontent.com/39955851/134506545-a7145fa0-79c8-4ea3-9c4b-4470e0bd753f.png)
