### ISSUE TITLE
[BUG] crash when joining minecraft version lower than 1.16.5

### ISSUE THREAD

**Issue by kvr25565** [MCCTeam/Minecraft-Console-Client#2110]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.12.2

### Console Client Version

Latest

### Expected Behavior

Join the server without errors

### Actual Behavior

MCC crashing when joining the server lower than 1.16.5

### Steps to Reproduce the bug

1. Join the server lower than 1.16.5
2. MCC crashing

### Anythings that could help diagnosing the bug

```txt
Minecraft Console Client v1.19 - for MC 1.4.6 to 1.19 - Github.com/MCCTeam
[MCC] [Settings] Loading Settings from C:\Users\DarT\Documents\mcclient\MinecraftClient.ini
[MCC] [Translations] No translation file found for en. (Looked 'C:\Users\DarT\Documents\mcclient\lang\mcc\en.ini'

[MCC] [Translations] No translation file found for system language (ru). (Looked 'C:\Users\DarT\Documents\mcclient\lang\mcc\ru.ini'
Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]

[SessionCache] Initializing FileSystemWatcher for file: C:\Users\DarT\Documents\mcclient\SessionCache.ini
Loading Minecraft profiles: launcher_profiles.json
Loading session cache from disk: SessionCache.ini
Ignoring session token string ',lenin,0,,': Invalid session ID
No sessions could be loaded from disk
Login :
Password :
You chose to run in offline mode.
Saving session cache to disk
Success. (session ID: )
Server IP :
Loading Minecraft profiles: launcher_profiles.json
Loading session cache from disk: SessionCache.ini
Ignoring session token string ',lenin,0,,': Invalid session ID
Retrieving Server Info...
{"description":{"text":"§4гриф сервер"},"players":{"max":2000,"online":4,"sample":[{"id":"c72051b6-c8f7-3479-a1aa-d9d2bb4c4c47","name":"satananindzvan"},{"id":"d638e6f7-7ba5-3ec8-a238-779e64656e04","name":"vadim324"},{"id":"abdfd133-c1b0-3a6a-8001-56d4b32a8ab2","name":"Neywid21"},{"id":"58729e6c-ef12-38e6-8d61-49216d8cacc6","name":"S1mple_77"}]},"version":{"name":"Spigot 1.12.2","protocol":340},"favicon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAATuUlEQVR42uWbeXCc5X3Hd/fd99j7\nevde7epCt7TSrrSry7ZEsYVtCQtjKmPALoQzhhBjKPcRCGQajpBhCCSEpJkMzCSTPwJkCk3SDCm0\naZu0HWimTTtJSQoWGGzLNibl1Le/53n3eHe1l215JiWj+c1er97n+X2e3/Ucr2EUf9x/huO6fLmK\nnOjf8imQkwGQXc5y0X83RjcdXx7HxPIk1iyvwbrltVhLsuajtZh8fw3WkEy+R7+RTPx+EqNHRzFy\nKKPJUlaTQ9prpkxGl8YaFPr/A3S/AyMYfnsYwweGka4gqbfTXIYOMEkhtUSfj9D176aR/SjbCICR\n0tH5MIvhY1mkl0aQohsO7R8iSSH5xiBJEsnFJAbYK/9cWwYqSHKVZaBGu8k3BzHy3sgKKzFUM830\nO8OVlVs8NZ0/5cL7ncTI+yN1AJDyw0fSGOCj+/9Q0XqyP4nsx9kqAEj5zLsZrnzyk6j8G5oVpI+l\nC7GuBEDm/SwpP/iJVT4vg4dSFSyA+T1FzeQfAQAWEFdaAPlFPlh80gEwN8h+mOGDXgAw8kGm4ZT2\nSQCQzwZFAO9lKqQOLc8P6FJJMh8gF/N1wKnL67VSWiHH5/qR1Afu/O/6/pbJ8P+WA6Av9OY/yPzk\nwCgm9k1g7FfjGP3FGCZ/ThXfL6ga/Jd1mH7ldGz49ZnY+NYmzL47h5l3zsT4gYlch05hkUP3Htmf\nwdTSFLU5g/WvbcDkS5PIPkNV7DOkx/epKnyOKsC/TWP4lRFk3sxqA8VBFGGkjw2XAki/O1z4cejN\nIXR/oxtSRIJRMsJgNMBgqCxGsxGWiILwTBi9t/RilDoxuji2uqmUlB56I4X1RzZg82uzyHx1BLFz\nmmBtssJgMlbtGxPBIcDaZ8Vpf9NR0qfU0XRlAMzkx49MwN5rhyligqmFpF+A0E6vJhMUUYYiFUUW\nJUhmM8z0m9GodcY75kPff/avGoTsW2PY+upWtF3YBpNsKihnovZYu2bBDNks8r6w/pkFAUY//TZK\n/aa+G1xGeD7jqQPgWBHAmt+thcljgnWXFfI5MsQNIoEQIFJDVtnCxWaxcnFY5BKxSGYYqXPNTzWv\nGoBNRzdDTaswk8IKwWZt2BWp0KadhPXFqmh9kwiGwWaAuF7kYuoQIK+T0ffb/oJ7rgCQOpIqNDj2\nz+MQogKce5xw73HDttMGU8hElKWayjNxyjIEMkv/Df7VAUAdnj80D0EywSGR0rJcsV2HDgKzAoO5\nCEAYpsHrFtH5b13VANCM73ARQOaHWZjbzHDtccF9rRuOyxww+oxkYnJd5Zkws/Rc6kH/qwMnnR3Y\n/289uBUm0QSXohTacMrVIVhkhWIDA0AuulWBZcEKc7OA1pdaC6l+pQWwKjDvc89nYG4xc+U9ez1w\nXemE0WHkN66nPOukSAC8l3nR8+89J50RGIDtBxc4ALfFwkUPolJfmBUYJAJwJlnMVU7YL7JzfRI/\nSlSPAamlogVkfzwKc0zkynuv88L1aReMNvK/Kg3mO5PvIAdwsRfdL/euigtsP7IAQRHglhR4lPoQ\nWD9NFPiUTTIfROelDog9IuLPxavHgKFDQ8Uc+YM0hLDAAXgIgGOnAya/iUf7WsqzznkpRjAX8F2h\nouflk7cAlsMXji3AFrXBRVmH3Z9JNQgsOEpmAaY4Bb6N1K89HjjPd0CeUBB7pqkGgIOpQvU0/MIw\nz/+ePV44L3fxdMhMiudVisSsAask8oBUrryHhF3j+5QPPa/0rkpRtPnwZsSmYrBRdHdSqnOK1DaJ\njfpgpUFhmUGi1MfA8xRJ/m+0Uz9Pl3n8ss/bYNtmQ9NfxWu4wMHhwlLX+D7KAjYBjvOcPB2KbSK8\nV/vg3OqCmKAUI+SKIAaEIj5TOC/sO1Y4he8Koe/V/lWp2yffXoPBawZrFjwGxUBuSyBSVAusV2AM\nEAyZvktSfZBR4NjtQOKHNQCwRcSCC7yZhn/aD5OVKJ4mwXe9D+pNfgRuDiF4axDB64NwEQxlQIE5\nYuaQjA4qSAJmiFERUkJC4smyOmBRJ7Vq/MWVy1jsPrM/nSO/NsG52QnHJgdsG+ywnWGHY6Mdzm2U\nrXZSwL6MYtZuL9xXeGDfQYGv3awNFqVE910etL7QVpgb1ATAGmz9WhsnKzaTmU3Z4D7XDd9VKkIE\nIXx7GJE7oojeGUPo2jCH4d7qJvFA7lbg3uZG90vdmD5wOmYPz+Gsw1tIzsIWep0n2XJknl7ntde8\nsM/8Ou3aOZLZw7PYcHAGo/vHMPXGNBwJB6R2SnUTNvgvDiB6Ywyx26kft0cQvjWM0I0h+PcG4Ltc\nhfNsJ+RBmVuB2CPB86APna90VU+DgzoAeQjRB2IQeyWY3KbCfIDFBjbSMnXE0k1FUdIKMS7y74wW\n9puA9kfbceFvLkT21ixaN7cgko0gvi6OxFQCzVPNSEw3o5nJ6S38ff4zf5/7PTGdQJykbbYVfRf3\nIf33w+h4ugO2rL3ggtzXFSNvl8cok6E4bxENkPopXlzmgpeUD3wjiIHXk425gB5C1y97EP9eHOrn\nVXh2U02w4IRt2gYlqUA+jaSLQAxZYJ+0wXOeF9EvxXD2r86GLWbnLiRGqBKzC1BMFDgpUNlJbELp\nezsrsXXfsVeZ1fgeAp2gytLDJjQW9P1mAP37qE//0I3EEwkE9vq5+VunrbxP9k12uHa6eOby3+eH\n76EA1Ef8SPx1C/p+N1AyNW4IQHFNYBD9dINugtHxs060/aQdrc+1ouXpVrQ+3YbWH7Si7fl2dLzY\nhb5f92PT85tJcQmBBRWBHX6IARF+SmEhyhZhJoqMsCyRyIjIMn/lwr6n39l1HjbJisnwn0fx51wf\njbQJ8cfiBEDLVAO5KW4vtdf58y60/agNzc+2oPlpsh6S1p+0ofPlbvS/ltSuL9OrFMDyKN/4qJeP\nSxYeFgdL5tcDuYDFvj/j8fVQ2hWufHBXEFKIYEiacpGc0vXER3W/2ScicmUErbe1wtphReCaILr+\nsat04XaxCEQfQLWFnOobN+l30rolMbYXcHBkVRYtUotpTN6zBrYBGyKXh9F1XxckVUKQqrj8iEeo\ngGESJSB64d/nrglQjlfiCnoe6kH3l7rhnSKzvojM+dsJ9L9+cnsWAxzAMLJYZQBMRvfT1OqmLNRN\nKrof7IFv2kcFihFhGtG88kzZGEkTFU9xiyYxPQi6LkTXm8js225pRzdBUGdU+Hb60PRIDJ0/6zrp\nmeZIyZLYsraheTLrc3mzmz74J8jekkVkRwzedV5eHAXKlI/XkDwEZi02wcTdp/3WdqjrVXjP9xKA\nOOKPN6Hvv/oLceBEqk2+T1hqAcONmxA1Org4hCzl5+mDlOuPzGHbsXOx4/fnY/dHu9G1vRtSgHzY\nYOTBLyIXAcTqAIjrrIBZjULWYxSpIAvJ8GzzcACxh5sQe7QJrc+08qDc/9uBIowTAsBWhBoEkKIq\ncXZpDpv/bhbT35pG9gsUQK9PofeSPnQsdCCxIcHXCUU28qRwWOfX0TKzrwpAKcaDEImdan2W281B\nmgvMODXZ7IJzjlWFJBsdUD+touvFxl1jJYBDjcWAs986G6G1Ia3gEAyFosREn9mSFcvfDupwiCnP\nTbkUQLwBiekCYphDtPCsoNC9Tbk5iNGYe6VCSHALMFqpbgia0fvLvoYgnJALjL01jtS9KcrrZjjP\nYuWvF/YxKk/JTH2Uw1UWvanDwXy+P0EAegsI50GSsPuy+7N2WHsOkVWkElznUIG2xcUr1vDnwg3t\nb1Z2gTr/OL00jc4rOqnyo3qfGvVs88KStMFClZtqqQJAsZQAOJ4YUA4glIPgp+9VAuCWWAkucgBs\nLqIM0qxv3lGy+NkwgNSh+haw4egMWra3amVvDgArh+1iDoBSBBAqsYLGs8AKALr75AGoOQA+hVIl\nzQO826lavESFbQ0NRtaCzn/qLCnSGowBjQGIrI/Avs7GLcB/aQC2Phs3xTwANjrBXEeLVlDqBtEa\nvh8t8f9SAHoX4O2RmAQj4rclkLi7Gep5KpS0wsvg47aAoXqlMMkZR9YjuiEK2zo7wp8No+VeKlH1\nACxVAJSVwHkIMSUnVarBcNk9CuavA8BWgeI3UG1wdwLqBQQgpSDxbKImAFavZD7IHD+AqcPTiG6K\nIbAzgObPN2sAeq1wki/qAayIAxUg6EtivdK1lGf39euUzwNo2tvEAfh3+qEMyUh8P1F3lenEACxN\nITZHAC4O5QC0wNJm4Wt0+k7VglBvQlRu9nnl9cEv3w6LAaKRIj9NmJqYBezQADR9t+n4LWCwAQDr\nmAUQgODFQfK5BJrvIQAtFr5AyTpTDqGSK+RjAkuPYaVMKlwbrDH6bBGWLcGHLg2j6a44fBeqkAlA\n5MlYXQDZj/QAPs7yg4aNAYgieFGAmxyzAkunlQNgnSkHUBNCA1JLeQactSkRAPV8P2KfIwAXaACC\nT4TrlvIlR2TGPx7jJzDrA5jiAAI0LWXEEwTAlmJBUOuM1yLVhBBqUPFQg8ozkU0CHKc7CEATfJQO\nOYDHg7V1OTBUODDJAUwsT/Djp/UArF1apwH4swAHwPzO0mspAiApdwVVLo0JegmVva+keLnyedPX\nA5CTlFnuiFI94NUAfC1U+5QYA6A/JdaoBawhAKG5MPy7/Jx4nCDIzVQISVJJp1ZA0FkDU6wSjIqK\n11GeuwBVoVKXiPBNYQ3AoFQfwKEyAFk2F2gAwOTSGgIQIgAqondGOQSlbSWAihCUYvnKZnds4dOi\nE4UthpoF/puX7qeP9uVmr98ek9kCai+N+t4AvAsagMBX/TWDYOpo+TlBtiZ4MN0QgMBsAOouHwGI\nIHZnjC+Psy0q1pnyDnr1KYvt2pKC2tK6dnRF9Jhhdpkh+UXIUQlSkJW2Jr6I4tUBrKZ8fieaLX+r\nV/ngWfBwAOpjgaozQr5sx84HLZcBSB9oDIA6y5amvIjcEeZ+J7VKsFIWYJ3R7xHmxUPpjoFgystR\nGfFr4zjtC6eh474OdN3fgc77O0k60MHkLzrQdnc7X0Zn0d0nr1S8fGM0D8D9KTfcf+qBRDHA/1h1\nC+BH5HI1wHEDmDg0gTC5gPdCL98dCt8S5vuGCpXClXaJ82IRzHxVp+kayhzXJRDZFYF/3g/vGV54\npmgqO+aCfcQO+7gDrhkXLAMKtxS2GVoCM7c1ziTfHjsnJKdoanyuHe5zXXw3SH1MrQlA/0yEblm8\nPoDxpXGKAUHKt16EbgshcH2QALADSkLJAYm8Nbipw2xLm+8qOwUYZWNhR4ft87END3bugO3dlZxE\nMxv5NdwVdKNeaUucLYooYwqsZ1n5nqFELuB7VK3uAvsHS54ZKM4Gl+qvCI0eGkWQALDFydCtZAmX\neyB2ihApEOnPCuRBsA5bRG05i22yOnc44btRRfCLQYS/HEaIJPhQCMH7g/DfQ7HlZhXe3R7Ytzpg\ndGpb3fqDF+XKs7MA7BrlDAW2WRvkjMwBqI/5qgfBt4YqAxg+XD8LjBzMIDBH0XaHh+8U2xccMPeI\nMAumiocmmLAobclQinsoqMmXSfnHI4g8QfL1aE4iCFP1FvlmBCFKYYGHqI1bfHzPjwXYvOLlB6T4\niTSrEdZZKwGwQkpLGoDH/VUD4NDhVOUHJkbeqb8sniULCJAFeAiAep3KGxb7RL7urz+hYaPgxQ5Q\nsIMLzEddVxIwUj72VIxvndVas2O/sS242Hcow/Rr7sMCHQOpULBlSlvY+iC9igSenQmwbrbCMmvh\nZwOkIUqD3wxUvffI+5nKADL0Q7LOYiJ7gMlPFuDe7oZjl4M3LPVJucMSRi76QwsmMmPm9+7PEoCv\nBPhSVSMLlixQdf9HD/dtISBACFL6tBiLu7/G3E6wbOBWIk/LUDZRSmQABkUEvhVcoQtPf0dS1Z8Z\nYo+RlByMruQCB0aoDvDDOmOFspFSUEaC4DPBOe+EfcYB+3qK4nMuzUWuDsB3hY8HO/eNHsSfTTS+\nbs/2+l5Pwr7NDrFDhG2LHbY5G9SrfQhc64d/jx/qtQH4/5ymvyMK3woX+8gihigeJc0IfDtQYTBp\nCvxRpvZTY4NvD9WsoNgTY4GtQd6Q0CrwVVj3peQON6nw3xzUTpDcREHyMz44L3DCut7Ko7znPh86\n/7Xz+J5GoWsD9/i5FVk32mCds8J9iZu34b+B4O71wXW5G9atVgjtWoHFrESelBD6brgEAAOf3w2u\nCoBlxvTRdN15dPi6iHYwgQWoGcrd8yRzJJuok2vJJZISP5rCzZZGRllH0+SvqIVt6uPZfWr7aRtM\nHu0AhLnZzI+6sSDHRlvoEGDuMHNh741uzf1su61oYQciF4t9Zifg9A9KVQZAxUHmg5G6AarnlR5t\nZH3UoEU7iVHwSYXAuIwQmljnRFi3WOH5ogfNPz6xc8P8lMqTUcjjVPBEBH5vg5XacBq1c0n0mb03\nOCjehE1Q5hX4vu4j2PmtMi3qV1O+4oOTQ/zAZG0IrIGWF5oReopqgYe9cNzlgPNeF1wPUDn6oBue\nhz08Fwf+MsiPpuU7dEJb2ey80out5Nch+B4hs3+AKsf7WVsk9zvhIPE+6kHwKcoyzzeh779zO0Pk\nzpUelKwNgP4yH2c4NQ1CZRl4I39QQtuQ5Gdv9hVlYF+ycMIruZg8qSfRBvKHM/L3en2AA+3/H4K6\nbyDXVrFfg1TosMMPvNxt4FliQ/mzwgUUZDaZD49fsh9kOflVk/dHyDUbaJuuyT8IdVwPT49/OE7/\nlP3DfcB9+RRdm/v7P8UJ+XpTB1GdAAAAAElFTkSuQmCC"}
Server version : Spigot 1.12.2 (protocol v340)
Translations file loaded.
[MCC] Version is supported. Logging in...
[MCC] Server is in offline mode.
[MCC] Server was successfully joined. Type '/quit' to leave the server.           Unhandled exception.
> System.IO.InvalidDataException: Failed to process incoming packet of type ChatMessage. (PacketID: 15, Protocol: 340, LoginPhase: False, InnerException: System.InvalidOperationException).
 ---> System.InvalidOperationException: Queue empty.
   at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
   at System.Collections.Generic.Queue`1.Dequeue()
   at MinecraftClient.Protocol.Handlers.DataTypes.ReadData(Int32 offset, Queue`1 cache)
   at MinecraftClient.Protocol.Handlers.DataTypes.ReadNextUUID(Queue`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.Thread.StartCallback()
```

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Found the issue, currently testing the fix.

**Comment by milutinke** [comment]
Works on 1.16.5
![image](https://user-images.githubusercontent.com/441903/185699307-8a5f76e0-b338-45ad-a88c-ba131aaf5cf5.png)

Works on 1.12.2
![image](https://user-images.githubusercontent.com/441903/185699769-7a1c6a73-ba06-4a06-a1ec-6fce3482e6eb.png)
