### ISSUE TITLE
[BUG] Replaymod doesn't work

### ISSUE THREAD

**Issue by kvr25565** [MCCTeam/Minecraft-Console-Client#2119]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

1.19 latest

### Expected Behavior

Working Replaymod

### Actual Behavior

Replaymod doesn't work

### Steps to Reproduce the bug

1. Enable replaymod
2. Join the server
3. When replaymod is trying to save the replay it's giving a lot of errors

### Anythings that could help diagnosing the bug

```txt
Minecraft Console Client v1.19 - for MC 1.4.6 to 1.19 - Github.com/MCCTeam
[MCC] [Settings] Loading Settings from C:\Users\DarT\Documents\mcclient\MinecraftClient.ini
[MCC] [Translations] No translation file found for en. (Looked 'C:\Users\DarT\Documents\mcclient\lang\mcc\en.ini'

[MCC] [Translations] No translation file found for system language (ru). (Looked 'C:\Users\DarT\Documents\mcclient\lang\mcc\ru.ini'
Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]

[SessionCache] Initializing FileSystemWatcher for file: C:\Users\DarT\Documents\mcclient\SessionCache.ini
Loading Minecraft profiles: launcher_profiles.json
Loading session cache from disk: SessionCache.ini
Ignoring session token string ',Kostya5874,0,,': Invalid session ID
No sessions could be loaded from disk
Login :
Password :
You chose to run in offline mode.
Saving session cache to disk
Success. (session ID: )
Server IP :
Loading Minecraft profiles: launcher_profiles.json
Loading session cache from disk: SessionCache.ini
Ignoring session token string ',Kostya5874,0,,': Invalid session ID
Retrieving Server Info...
{"description":{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Добро пожаловать на сервер игрока "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"CloutherPeck1"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"!"}],"text":""},"players":{"max":50,"online":1,"sample":[{"id":"a8d67f78-6ed4-3b0a-9035-f428354a128f","name":"Vagina_Slona"}]},"version":{"name":"Spigot 1.16.5","protocol":754},"favicon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAACe0lEQVR42u2bv27CMBDG8wLsHUBi7zMw8BQ8BAsTbxBVqsQTsDB0qoQ6dOzQVpW60UhhK0OKqgQaoGVhxT2jQ4JAII7j/MGH9AkJgePvhxOf72zDUPxaLpdVUANkgvqgAcgFrUBr1Ao/G+B3TPxN1SjiCzpeB3VANohJysa26nk3fQVqg6wETIfJwmtc5cl4GYesr9B4UD5es5y1+RbISdF4UPzarSyM10CPGRoPivellpb5JsjLkfmteJ+aKo2XQLc5NB4U72MpafMVULcA5rfifa0kab5XIPNb9aQh4LDvFtD87kgoyQDYu+evb4aFUPCZIPO0ZxcAgAnPDjjPexcEwBOKE8KCnAID2ARLIuEtu0AA7GzYjAsbRwTAu+2xz69ZJnr5cEUBOCcXULjCYiIAeEeymuaGox9RAFzmqfW8HxfAfPEX+Z+b+L8HbU/hs6i/lwTgH80nYKKBxQXA36Peo3zoBtt+DRnOpwzGBMDVPgbA0giAdSyHxzQCwPZyjJh01A1AZxeArSEAezdvz1QBkJnmzrUpCYBt6g5YgNAVQONs8JMUAHe62AzzKJpinJACANPAUpRyAGGdVdGmAIC+gfU4XQEMDCxKSgMIC4VlAMRtUwCAa2BlVhpA3IWLijYFAKwMLE/rCmBNAOgWSOgh+D1ZsLsn50AyAOK2KfoQ1H4a1D4QSiUUns2jp8z4/J9mKKz9Ykjpcng0jp8U5Sl35cth7RMilBKjpCilxakwkkRprEC1QT90q63WxdG45fGHt3HkZGfSun8eJ1se136DBG2RoU1StE2ONkrSVlnaLE3b5enABB2ZoUNTdGyODk7S0Vk6PK3H8fl/jJTy82KQfKcAAAAASUVORK5CYII\u003d"}
Server version : Spigot 1.16.5 (protocol v754)
[MCC] [Replay] Start recording.
Translations file loaded.
[MCC] Version is supported. Logging in...
[MCC] [Replay] User UUID: 0dd52773-f132-394f-b530-06259c469ad4
[MCC] Server is in offline mode.
[MCC] Server was successfully joined. Type '/quit' to leave the server.
Kostya5874 joined the game
Please, login with the command: /login <password>
<Vagina_Slona> пропиши /reg пароль и ещё раз пароль
Successful login!
Welcome Kostya5874 on Your Minecraft Server server
This server uses AuthMeReloaded protection!
<Vagina_Slona> пропиши /register пароль и ещё раз пароль
[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)



[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)
>


[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)
>


[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)
>


[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)
>


[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)
>


[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)
>


[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)
>


[MCC] [Replay] Creating backup replay file.
[WARN] Update: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvide
    at MinecraftClient.McClient.OnUpdate()ure.Update()ckupReplay(String replayFileName)
>


[MCC] [Replay] Exception while adding packet: Cannot access a closed file.    at System.IO.FileStream.Write(Byte[] buffe
    at MinecraftClient.Protocol.ReplayHandler.AddPacket(Int32 packetID, IEnumerable`1 packetData, Boolean isLogin, Boolean isInbound)
>
[MCC] [Replay] Creating replay file.
[ERROR] Disconnect: Got error from MinecraftClient.ChatBots.ReplayCapture: System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterPr
    at MinecraftClient.McClient.DispatchBotEvent(Action`1 action, IEnumerable`1 botList)ng message)
>





[MCC] [Replay] Exception while adding packet: Cannot access a closed file.    at System.IO.FileStream.Write(Byte[] buffe
    at MinecraftClient.Protocol.ReplayHandler.AddPacket(Int32 packetID, IEnumerable`1 packetData, Boolean isLogin, Boolean isInbound)
>
> ^C
```

### Device

Desktop

### Operating System

Windows

**Comment by z7087** [comment]
same problem

**Comment by BruceChenQAQ** [comment]
Should be fixed in https://github.com/MCCTeam/Minecraft-Console-Client/pull/2124 https://github.com/MCCTeam/Minecraft-Console-Client/pull/2124/commits/75e7b0e37d1a0743e04a51ab0e244bf8e27fe228
