### ISSUE TITLE
[BUG] Not properly connecting to server

### ISSUE THREAD

**Issue by samidont0817** [MCCTeam/Minecraft-Console-Client#2129]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.2

### Console Client Version

1.19

### Expected Behavior

Expected to be able to properly log into the server.

### Actual Behavior

Not letting me log in using mcc 1.19+ as the server version. However, upon logging into the server with 1.18.2, it sends an "Unhandled exception". It successfully logs into the server right before the exception.
"> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type ResourcePackSend. (PacketID: 60, Protocol: 758, LoginPhase: False, InnerException: System.InvalidOperationException).
 ---> System.InvalidOperationException: Queue empty.
   at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
   at System.Collections.Generic.Queue`1.Dequeue()
   at MinecraftClient.Protocol.Handlers.DataTypes.ReadNextByte(Queue`1 cache)
   at MinecraftClient.Protocol.Handlers.DataTypes.ReadNextBool(Queue`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.Thread.StartCallback()"
   That is the exception sent.

### Steps to Reproduce the bug

1. Open MCC.
2. Log in using 1.18.2
3. Join Server

### Device

Laptop

### Operating System

Windows

**Comment by BruceChenQAQ** [comment]
Should be fixed in https://github.com/MCCTeam/Minecraft-Console-Client/pull/2124 https://github.com/MCCTeam/Minecraft-Console-Client/pull/2124/commits/dff3f23b0347c60c1f09c3e694674a7152baccc9
