### ISSUE TITLE
[BUG] The progress crashed when moving or changeing world

### ISSUE THREAD

**Issue by DoctorIDD** [MCCTeam/Minecraft-Console-Client#2403]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.12.2

### Console Client Version

Lasted

### Expected Behavior

The bot moved or changed the world successful.

### Actual Behavior

I let the bot enter an forge server(loaded mods and plugins at server side) and try tp the bot to me with "/tpa ..."command in a plugin.Then the progress crashed.It seems a problem of chunkloading,but the progress didn't crash at the beginning of entering the server.

### Steps to Reproduce the bug

The progress run on Ubuntu 18
1. Enter and login an forge server(including plugins)
2. Try to tp to a player in another world or just move without changeing the world
3. The progress crashed
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type ChunkData. (PacketID: 32, Protocol: 340, LoginPhase: False, InnerException: System.OverflowException).
 ---> System.OverflowException: VarInt too big
   at MinecraftClient.Protocol.Handlers.Protocol18Terrain.ProcessChunkColumnData(Int32 chunkX, Int32 chunkZ, UInt16 chunkMask, UInt16 chunkMask2, Boolean hasSkyLight, Boolean chunksContinuous, Int32 currentDimension, Queue`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted

### Anythings that could help diagnosing the bug

```txt
Minecraft Console Client v1.19.2 - for MC 1.4.6 to 1.19.2 - Github.com/MCCTeam
Resolving kd.mchws.top...
Found server cn-wh-dx-1.natfrp.cloud:12501 for domain kd.mchws.top
[MCC] [ScriptScheduler] Loaded task:
triggeronfirstlogin: False
 triggeronlogin: False
 triggerontime: True
 triggeroninterval: True
 timevalue: 14:00:00
 timeinterval: 53.4
 action: send /hello
[MCC] [ScriptScheduler] Loaded task:
triggeronfirstlogin: False
 triggeronlogin: True
 triggerontime: False
 triggeroninterval: False
 timevalue: 
 timeinterval: 56
 action: send /login pass
Help us translate MCC: https://crwd.in/minecraft-console-client
Color test: Your terminal should display [0123456789ABCDEF]: (4bit)[0123456789ABCDEF]
Color test: Your terminal should display [0123456789]: (vt100 8bit)[0123456789]
Color test: Your terminal should display [0123456789]: (vt100 24bit)[0123456789]
[SessionCache] Initializing FileSystemWatcher for file: /root/mcc/SessionCache.ini
No sessions could be loaded from disk
You chose to run in offline mode.
Success. (session ID: )
Using Minecraft version 1.12.2 (protocol v340)
Checking if server is running Forge...
{"description":{"text":"§r                     §e§l我的天空§r §7§k|§r §aMy Sky\n    §r        §f追求创新与打造极致体验的空岛生存"},"players":{"max":100,"online":1,"sample":[{"id":"c4ffbbfc-1044-37e0-afd6-39e085b94463","name":"§7              §e§l我的天空"},{"id":"939ea5f0-ea05-397c-8d06-12b33f64fe37","name":"§7"},{"id":"5217e192-29f1-3444-b417-18a3b2f3d5b4","name":"§7§a✔ §b简单介绍"},{"id":"d06ad9df-44de-3c6d-b65e-26687b452770","name":"§7§f我的天空 是一个多玩法的高版本群组§r"},{"id":"83a14c75-0562-32d7-84ce-697717f59f68","name":"§7§f目前拥有 1 种生存, 其他内容正加紧制作§r"},{"id":"939ea5f0-ea05-397c-8d06-12b33f64fe37","name":"§7"},{"id":"541a99f9-eb97-3af7-9c6c-8beea786b78b","name":"§7§a✔ §b版本支持"},{"id":"f9b1622f-501f-38f2-a47d-6f49d9c5c434","name":"§7§f请使用 §a§l1.12.2 §f及以上客户端进入§r"},{"id":"939ea5f0-ea05-397c-8d06-12b33f64fe37","name":"§7"},{"id":"a51b038b-f22b-3a0a-b1ed-3f958b42db78","name":"§7§a✔ §b联系方式"},{"id":"210db084-d918-3a52-8a95-ee9b24a17bf2","name":"§7§f官方①群: §e538779726"},{"id":"939ea5f0-ea05-397c-8d06-12b33f64fe37","name":"§7"},{"id":"20f44c50-e237-3a7a-8c6b-3d039db8016b","name":"§7§a✔ §f全服目前在线人数为: §b§l1 位§r"},{"id":"939ea5f0-ea05-397c-8d06-12b33f64fe37","name":"§7"}]},"version":{"name":"1.12.2","protocol":340},"favicon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAATVElEQVR42s1b91cV2Zbmn3pr5peZ\nWTPvdVRb2gbbbpV0I4Y2taJEAwgm2kTGDCoZoVHEiBJVRG21zalNrW1AUAzA9/Z3qs6l7vVeBEF6\n7lq1qooK5+xvp2/vUwR9l+DG6G8utU2IN45DfM71fRPiXWoLSYzGN4ts+HJ+mPr794tn4Ns4J774\neSqCYx3qOu/zPGd5x4e2oNES2CNsorFpEILj3Bi3yI1v4/vvswpD4b5eEA73mkTsaTiMizev4e6j\nBzhz7SJKjtQgLGUuxsREYmLSNIQmyib7kCHMLWg0haeQYxa6MXahoSUKGpHswvx1LvyQ5PKAwOco\nzMSk6XJvJJK35+B5Vzf8/R49+wsLslPx2bwpykJoFd8ssivgtBX9rQB4hBdNT17iRmKuE/HZTkzk\ntVg3Cg44UHvGjoQ8pwImNJHW4BStR+Cfc37EzHXJePW6Vwn7rucdent70dfXp/Zv373zgLB8Rya2\n1ZZj674SsZZY9byyCNkGAmJ0LIBaFQByK53Y225HTZsdedUOrC1youKEHeWn7DJxB74TQMbHOcTH\nZyKnqhjVjYfw++2bSsienh61p/B6449A+P5eve5GVmUBPher+Gp+uIoXgUAYFQBo2pPExIuPOlAq\nAhc3O1ApQlfJVtriUNuekw4kihV8s9CFY+fOeAmkhbQKrs+tf+/p7fEAxWfyqndj9a5cTF42S7mF\nPxCCRivafy+Bb9dBB8pP9gtdIltZi3FefsKJksYp2Fy9AW/eUqgeMfke9PZZhfcGwRcAj1X09XoB\nde3ebYQvnycB1zGaFmAIzhQ3Ps6FKUtcKDkuAp8wBKbgWviyVjludaGo+UccP78Nb99SiHeGr39A\nYH+btgBag44TGRXbJUCGeWLCJwdAB78JchwsaS59lxN7xORLTO2XtZqbBwRaRCT2NMfgacdLbeSe\nfV9fr19t64Cog6NyBdMNrL/lOzaagTF69CyAe/r0yu02VLdRQGpda9wKggbFidLmMOw+kIELt/5E\nV/db3Lj3EF0vtV/3eAHgT1D9u3H/Dn67cRXPOztRdnTv6GYBrf3xsnck2VF0JBJlJymkaLvV2JeZ\ne32sz8vlvoLD4UjKm441hQlYsdONw2e24vXbXr+CvnjZiYzy7djX2iDCduFJxzNUNtRhSvJsif4u\n/Lj0J4xbGKVS64gEwUBI+v49VAD4UtJa5moXmsujsLvV1L5FeKvgxrEBSMVJcZeTNpQ1RaCqzYbi\nlqnY356Caw9ahBA9RPebDjx5fhd1J49h+i8J+GzuFGGTNkxNniMR/ydl6qTInEewpMCQhOiRSYMT\nLCwtxOJL1nM9CIPfWNFAygo3zmwS4RoN7SsAmkXIEw4UicAlzVZr0CA4LHHBcI1icY2ipjCUt0YL\nKDNQdNyFcTFhQp5sigaHKGEdhsA+fj5sIuQRSl5MZBlNifL4WLtCXp8bgusixq04/5cxbqRm21Gt\no78IXiLxoLDRhqItU7GtZCoqTjsVKB5LaLGA0KItxGnEiBabAGmTlGmDM8Upph3tVUB9SOAhA2AV\nnkVHhORTppQDpxrQcqEdDb+dQvmx/UjanK4YF0ExNOBSRc70lS6UNjhUDCgSDlB0MAq/7olC/ZZI\nXBJaXJUfji31kShtcyj/t7qGdesHx6EsqVL2c1Y5MS7WbVaTHxevgj7kzxQm1BQ+tTATj58/CRh5\nT/x+VgFEECaI301e6sLOQzLZdgd2HbehtiwKF7fYcX2TE/XZbiSIezRmRKEuLxylu8OxvTbCA4JX\nqvTKFuI2clzVZEdMqh1jRxqAfh+OVoKwDienTi/K9wjK9EPaqciGSTg0XWX6iVg+F1/FuLAs041q\n+nStDWcK7biU70ThehcWpbqEGQrvj3WiaK0NV7a6cVVo8L6sqdjZECWs0DtDeO0FhGJxpwOH7FiS\n5sKYuBEAwNpAoOD087GSOpyrF2FexjIpRzdI5H1tCN/7flHSZ56/M1nX0fYW/N+cyahcG4bWnDCc\nyrahLtOFWSmcsDFpDTSJUsRil2gzGuvTIyQW2FScKG+1+r9mjsa+RKyksUwsQCxsbPwwAdAdF619\nRtIfJZXUttaj89VLoZJvFR3VHNuXkvqjpm/kmZ0Hq9BYm4Mjm+diVWoEpiybJv4qE+V4XnSZxZIL\nn0u8mJUchaK6CJUddjbZVMygS5S19GeQEgGn8pgNR/Jknqp0dvkNgkOyAGqbAYzphOdnrl7w8u2+\nAEIHoqaeY9k6XnXg+OltONYeh5zyGAmMTh93c2GibF+JL+eku3B+UySKMidj/7YI1BRFoqDOIFG6\ndigWAPYftGHVSie+9vj/MABgGluYk4bzNy7julRN7abwPRZuHajg8FeWWvm55u/yNvx2JxeHWxYi\nTMri4Pj3afN4cQu3mHRNlhvHNthwNt+FK5tcqN8Yjh37JTiekhQoga/slMSAmihMSdDvcQ2LtQZF\npP6MZ50vvOtvNfFAlZdVUGPzV67qrbfXiAu37h3Fqa3hWJASLQTJ2281df4mzq0qxx+S3KpF5k52\n4dcMASQ/AjuORqGizWig7NhnR2i8tYk6DAtYkLVCfLZPtZt6enpVIOs1hTGN3xS4D2a4M/8GL1A8\nf7c8ozYzO9y7XY8t6eGYpDq4vprrL515zgYKfXucgPGNHFeud+LI1ghsEksoO+PA5iobQmONSnPY\nFmBfuRBPOrt9TNpIdb4a7S854SWkBqS3t8+rLFXvMTPDvdPVmJYwRaL2NCXohPjAzVO9haqCyrCI\n+iwXmjLDUVEYjv2FLkwiSMPUvhEDJAAuL8jGtfsPcfevZ6g/exp/PH7an+/NnO/hAGbu9wbGuzT1\n7dy8efMWBVuW4oe4KEWQBme22ircqqoMWxKNYrGEC1lMqW5T+0OjvQGzAEGYtGQmItPmY6wwvvlZ\nqbhy974I2m8VHS9f49yNm5ASPeDvwZOnOH31Kl68eqfK19dvenD38ROk7MjEVwsiPcK/r/1AZMxg\norSYMQvt+DZxBmanTod9sRQ9mkf47D8KAA7CNKhXWZgWfxBA0gpzsb2uCnk1pZizMUUNklqYjVNX\nruDek+d48uIVHnd04dbDR6hpPi73JGNd2Vbcf/oXXotFnL91HY5VC1WhpOuDCR+I3FaB2MikQji3\n7D2FaBWqvf90CxbkrlJzHa7wHiLk+0cNyFcLwvGF0GAuNtBKeC9XadhcmJoyB8wgbDay6cD2c1Ta\nzzguxdHNh/fw4NlfqGo8iO8XTx+yqU4wydLcjGSs3JWDXYeq8efzpwLsYzx/2YnLf9xEaf0+pBfn\nqzWA8bGOYVJhn4npcxZBXGpSy00mW9Q9NTJGDkxNfGs2HXgPW9COlTGYtX6JAunbAbTkF3y20UTz\n09LjcfHOdTzqeCZB+oUI3oWHz57gWVenxKo/ce3eHZy8/BsW5q5QFuuvBzCscniwE/a9rktiEix/\nCxIG9e3v0vh7L8GlZVU1HcKlOzfw14vnyqIeytb1+rU6/+PxQzRJOc4sNmwLGKm2mLcmo9/zaeW3\ncjxp8QxxKZvS9IQAwYzgsa+XkL8aB9ualFvdfvQAF25fw4G2Rhw63Yz8X3cr6xx2FhguACEW7Qd6\nhteYZajVpgunsUb817ZiwXtL274gEChaQ9LmX5BakInpaxNVzTJl2ez3gAu0LD4QQMNqimpz16ux\n1Jg/S+A98ZvW4Pr9P1R26H77VlLlSxXVCUqwHxO29iXoEmNjotSmrYZjB4oh2s1GrCf4nmbijcbj\nzLVJSNyUjhnrkpBfU4zD7c1YsTPbE5SCzUlyskyHG8q3Ibtqp2yFyKjcobQ6cRAmHGIGY4MTRA8Y\nfwgQ38k0TuBVah9AlqCPXfBI2ZGBtivnlW9elSqSQYnRmVpdLqZadmw/finZ5DFxToR8gBvba2Nk\nP9ZMrYHcKtRsx/FZuoLuXVj7lFpw3s90nLYzCyVH96HuZINaKrdLRtJW4+umPB8yAHwB01vrpXMq\nKt9+dF/SVAdedL9SKYq5mkAwWp+9fglhcm+wJU36btZPYXSa5TFBIv/48ucwFSvICdh+59+/Mxs3\nJEl8ZsnWdSioq8SR9hbFF5gyn8nGfeP5NszduMzDLZimrWAHDcX8tT/SHH9X6alDCdsh/szUdEes\n4OHzJ8ISH6nIva50iyJCg0mfWpsUmsfzs5ar5zdWbMcJyfePhQ9QwHjJCrzO5uvCnBXqK5L9J48r\n8Lted+PlmzdqPlTIKzl+JfHm8t1bqG4+jF9lOyGKm71hqep1Up6goQY+aqD46F71Yg66t/Wo0OVy\nJEiQS9ryC/IkNZGh2VfEKD8clPAJxkdQPM+U2FDZcEDGqEFFQ50iP/wRYJKig6eb1L28p+3qBQVY\nSkEGGkTTv928olLls64XCohOAeSpHNNCuSenaBbuME+sadxQANCmycHoX9WSylounsHF29dVEcUJ\nHTt3EjUtR1QHebzJ030JkK/g/cLbFa1ulnfuqKtQLsYJ/sM5TsCtUBqctWGJCrZ0h3/NnYx9rfWK\nDvOY75u0ZIbKKItyV6pgm7WnQAXk2LxVopBNypp+Wr/Yk6kGHQR5I6PqZzJQbvUuxb4oMP2r8OAe\n/NeMELUwwt/uw9XKZ2mWVlZnZWr+0hej9SXh96S2/+Ear+oKPjPtlwS1AMMMQvB1VOc13rt4y1r8\n76xJnnfqYMl7qQhaK2sYfjzFd3LewZbxPxgEeQMDD18QJ77HiM9Akrg5XQnsWh0rJluAWvFB8vXl\nkhlYQFnrBX7GRq0Fm9UmNRVqieRMqYwpzCKsvsuO1SImO039jdrk82PNz+CM1EqaPBft1y6qPWMC\n50FQ9HsjUucp0HTUZ3awFmWDsgAdmIgoBbh2/w7mZabgv2eG4ujZVjUBgkJ3YNp719eHmWKivF9H\nd5o2MwErRJoqC6Tj5055PnS0Vp7RUvwwcNJ/2Vqh//K5tMJMr7RHMAjQjQd3xcwLle+fknQcbL5v\nvBrz8oBjDnppjHuaXfu137FWfIifrXEJ+oHU+/RVRmXy+uIje5VFGGvyTs+KMc2wtL4W525cVsAx\ngHFin8+b6lW90Tw1P6CmCSxNX/eYlm3foK5TizRvZgZGemp2QVaqAjlYWcA09e5AY4b6qRgDAhCq\n/H6K8u99J+qVb3OCyyXivhE6S3dIEBb4Pz9NRJ1MVruETmMaALoIrxOo56+6hEBtNOPENGW2BHh9\n2db+XG1+Fvuf7mCVUfhbU5SvnqEWv1AC7sOb3l7VF6AF8kNJ+jpjT8Ax54d5ud6Aa4OG34crX2dw\n0jmag7CQ4Y8BkFqh9tiw4K/+7AlEpS0wLEAEJBg0U76j6EgNut+9k8mmebIEBTp/86pKZ3SXf82Z\nrAQlAO41ceo55m2rVVLT/Ft8/hq0X72ojqlpz5jzAoxpfiY3oAXoQagVBiuSHRKSMSbjYl7ngDR/\nBiOdv2dIhUZOwBbo1toy9TwnQ3DY0bkl1pIkEZukiaBSWLoKAxxJU2d3tzC205JGj2JP40GVTmm2\nGRU7lMCaSfJ4qrhZ25UL6v2Rkjo7hfDwGW09gcY08v4giiEORM2y5qaWGUisNTf3HMRqSgx8syTH\nGkHQm98TNLbRVhflKQthOtX+T0vg9VW7c7FNgCOwFHqO6Q60Bt9GCq2G/F5bJNkg6xLNKz405gdd\nQKEsRKS66fB7kVMPEOrD4YksESYQvn09WgPfw8BJMvKl+a2eteYnoJwkwWawYtnrb5z+wOywZIUo\nL4UMNOagXEC/iKbt1WwI0LSw0lnfLhAF4OA0UboIA5+1TvfqPZofNvtG6kBs0vq/BNYK8UNjDioG\nDERhh1o50n1u/XlflcYMrP4i8UhuQx0zaKDCZ7gT1emUPqu7Pp9S+I8ZM+hTTsRKpkYK1JEeM+hT\na+O7EVrD+1RjBo3UQIN1pY9ZbxjK+0e1La5TEtNfIJPzWhfwSanMNP4Y2kC9hJEO1EHDDTZhUpKS\nCUZJxehpUPopOiaa934X7/Z0f35at1jVD9aVIk+/0GeBRV/TuV5zlhFZHf7YdMPKkJUX+20FBypV\ncUSOzhqduVg3KlgTMCqzkPrn7B9UicruLWk2OzfsDut1Rpa7PFfNCznv39sV6SFYtBqeR6fHqYpw\noAWZTwaArs1JXQnC2pLNyiI27y1RZTG7OVwMUV3bbevMfmGRsgIufFYcr1PVHi2AQizdtl59l8je\nIuktrYPrfgSJz/DvbHHxfWmFWaq7SyBJe/8WAEh92cTgGh0bJbsP/6pAoEZZpJCJ5VTvUlSU10lK\njpxpVcLRQki32aVl/449u9Jjtaq9TWC4rM72G6/xvfkCHJ9hoUUgWeMvyl2BTBlrOAujwwKApsni\nh92gmJw0JRjX6qlJrt8lSw0em7tSNTNic1epGBGbt1IVOtT8MrmP7WnW7FxdYn+PvX+2sowvVJOV\nsPxahcAQ7Li8VZi9can6Zpn9A9b5g2m7f7IswJKYlSP9UfslS2cef22u/NBNVLRX2cLwbf0Mswd9\nWq0UsYG5yMgm+hvlMWY8UO804wGfMZ43rv9tQdDapwuxRGZPpLauAFmuhfjc4y/ye30fZFlB0gWX\n73v+tjQ4ED/42Pv9VZ6fkl2O0n+P///d/g2m+GerDeCxJwAAAABJRU5ErkJggg\u003d\u003d","modinfo":{"type":"FML","modList":[{"modid":"minecraft","version":"1.12.2"},{"modid":"mcp","version":"9.42"},{"modid":"FML","version":"8.0.99.99"},{"modid":"forge","version":"14.23.5.2855"},{"modid":"advsolarpatch","version":"1.2.1"},{"modid":"anothercommonbugfix","version":"1.2.5"},{"modid":"ic2","version":"2.8.222-ex112"},{"modid":"advanced_solar_panels","version":"4.3.0"},{"modid":"appliedenergistics2","version":"rv6-stable-7"},{"modid":"mm_lib","version":"2.2.0"},{"modid":"patchouli","version":"1.0-23.6"},{"modid":"sakura","version":"V0.0.9pre-MC1.12.2"},{"modid":"flammpfeil.slashblade","version":"mc1.12-r32"},{"modid":"slashblade_addon","version":"1.6.0"},{"modid":"lastsmith","version":"2.1.8-1.12.2"},{"modid":"armourers_workshop","version":"1.12.2-0.50.3"}]}}
Server is running Forge with 16 mods.
Mod list:
  minecraft v1.12.2
  mcp v9.42
  FML v8.0.99.99
  forge v14.23.5.2855
  advsolarpatch v1.2.1
  anothercommonbugfix v1.2.5
  ic2 v2.8.222-ex112
  advanced_solar_panels v4.3.0
  appliedenergistics2 vrv6-stable-7
  mm_lib v2.2.0
  patchouli v1.0-23.6
  sakura vV0.0.9pre-MC1.12.2
  flammpfeil.slashblade vmc1.12-r32
  slashblade_addon v1.6.0
  lastsmith v2.1.8-1.12.2
  armourers_workshop v1.12.2-0.50.3
Server version : 1.12.2 (protocol v340, with Forge)
Translations file loaded.
[MCC] Version is supported.
Logging in...
[MCC] Server is in offline mode.
Forge protocol version : 2
Sending falsified mod list to server...
Accepting server mod list...
Received registry minecraft:potiontypes with 37 entries
Received registry minecraft:biomes with 65 entries
Received registry minecraft:entities with 133 entries
Received registry mm_lib:universal_fluid with 5 entries
Received registry minecraft:potions with 34 entries
Received registry minecraft:blocks with 502 entries
Received registry minecraft:villagerprofessions with 7 entries
Received registry minecraft:dataserializers with 0 entries
Received registry minecraft:items with 890 entries
Received registry minecraft:recipes with 1595 entries
Received registry minecraft:enchantments with 30 entries
Received registry minecraft:soundevents with 560 entries
Accepting server registries...
Forge server connection complete! 
[MCC] Server was successfully joined.
Type '/quit' to leave the server. 
MisterIDD, welcome to Mysterious Mountain Lib. Author's other mods link: https://www.curseforge.com/members/sz0999312/projects
Link: https://www.curseforge.com/members/sz0999312/projects
玩家 MisterIDD 进入了服务器       
[玩家系统] 请输入“/login <密码>”以登录
[玩家系统] 已成功登录！           
 DoctorIDD 请求你传送到他那里     
若想接受传送,输入 /tpaccept.      
若想拒绝传送,输入 /tpdeny         
此请求将在 120 秒后自动取消.      
如果你有什么 好的想法或建议 欢迎提交给服主哦~
如果你有什么 好的想法或建议 欢迎提交给服主哦~
如果你有什么 好的想法或建议 欢迎提交给服主哦~
如果你有什么 好的想法或建议 欢迎提交给服主哦~
如果你有什么 好的想法或建议 欢迎提交给服主哦~
已接受传送请求
传送将在3 秒内开始.请不要移动
准备传送...
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type ChunkData. (PacketID: 32, Protocol: 340, LoginPhase: False, InnerException: System.OverflowException).
 ---> System.OverflowException: VarInt too big
   at MinecraftClient.Protocol.Handlers.Protocol18Terrain.ProcessChunkColumnData(Int32 chunkX, Int32 chunkZ, UInt16 chunkMask, UInt16 chunkMask2, Boolean hasSkyLight, Boolean chunksContinuous, Int32 currentDimension, Queue`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted
```

### Device

VPS

### Operating System

Linux

**Comment by BruceChenQAQ** [comment]
Can't reproduce this issue when joining the server(kd.mchws.top) or tp in a local forge server(without mod). 
You can contact me at Discord and send me a tpa command in that server for testing.
