### ISSUE TITLE
[BUG] The remote certificate is invalid

### ISSUE THREAD

**Issue by DefiDegue** [MCCTeam/Minecraft-Console-Client#2411]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.3

### Console Client Version

1.19.3

### Expected Behavior

Impossible to connect
I have make "mozroots --import --ask-remove" but no change

### Actual Behavior

Impossible to connect my account on my linux server [ Rocky Linux 9 ]

### Steps to Reproduce the bug

1. Login account on Browser or MCC
2. Error directly

### Anythings that could help diagnosing the bug

```txt
Minecraft Console Client v1.19.3 - for MC 1.4.6 to 1.19.3 - Github.com/MCCTeam
GitHub build 178, built on 2023-01-20 from commit b79dd1d
[MCC] [ScriptScheduler] Loaded task:
triggeronfirstlogin: False
 triggeronlogin: False
 triggerontime: True
 triggeroninterval: True
 timevalue: 14:00:00
 timeinterval: 53.4
 action: send /hello
[MCC] [ScriptScheduler] Loaded task:
triggeronfirstlogin: False
 triggeronlogin: True
 triggerontime: False
 triggeroninterval: False
 timevalue: 
 timeinterval: 56
 action: send /login pass
Color test: Your terminal should display [0123456789ABCDEF]: (4bit)[0123456789ABCDEF]
Color test: Your terminal should display [0123456789]: (vt100 8bit)[0123456789]
Color test: Your terminal should display [0123456789]: (vt100 24bit)[0123456789]
[SessionCache] Initializing FileSystemWatcher for file: /home/deficorp/Projects/MinecraftLinux/SessionCache.ini
No sessions could be loaded from disk
Connecting to Microsoft...
Your browser should open automatically. If not, open the link below in your browser.

[[LINK]]

Paste your code here:
> Error: no DISPLAY environment variable specified
Connecting to Microsoft...                     
< POST /consumers/oauth2/v2.0/token HTTP/1.1
< Host: login.microsoftonline.com
< User-Agent: MCC/1.19.3
< Accept: */*
< Connection: close
< Content-Type: application/x-www-form-urlencoded
< Content-Length: 188
< 
< client_id=54473e32-df8f-42e9-a649-9419b0dab9d3&grant_type=authorization_code&redirect_uri=https%3A%2F%2Fmccteam.github.io%2Fredirect.html&code=REDACTED
Unhandled exception. System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, OfflineRevocation
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at MinecraftClient.Protocol.ProxiedWebRequest.Send(String method, String body)
   at MinecraftClient.Protocol.ProxiedWebRequest.Post(String contentType, String body)
   at MinecraftClient.Protocol.Microsoft.RequestToken(String postData)
   at MinecraftClient.Protocol.Microsoft.RequestAccessToken(String code)
   at MinecraftClient.Protocol.ProtocolHandler.MicrosoftBrowserLogin(SessionToken& session, String loginHint)
   at MinecraftClient.Protocol.ProtocolHandler.GetLogin(String user, String pass, LoginType type, SessionToken& session)
   at MinecraftClient.Program.InitializeClient()
   at MinecraftClient.Program.Main(String[] args)
Aborted (core dumped)
```

### Device

Other

### Operating System

Linux

**Comment by milutinke** [comment]
Try with:
```
dotnet dev-certs https --clean
dotnet dev-certs https --trust
```

Also check:
https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#os-x---certificate-not-trusted
