### ISSUE TITLE
[BUG] Ingame connection on some servers

### ISSUE THREAD

**Issue by erouins** [MCCTeam/Minecraft-Console-Client#2514]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.4

### Console Client Version

Latest

### Expected Behavior

Expected to be connected ingame in server.

### Actual Behavior

The mojang server's login requests are working perfectly. But the in-game connection sometimes fail depending on the IP address i'm using, and depending on the minecraft server. However, not matter which IP I use or which server I try to connect to, the complete connection is fully working using the Minecraft official client.
I tried using a paid proxies or a VPS. I also tried using friends computer which didn't work as well.
Nevertheless using a friend wifi worked fine.

### Steps to Reproduce the bug

1. Use this proxy : `185.96.83.86` SOCKS5. with username : phugo91 ||  password : tGvI9g4koQ
2. Connect to the following minecraft server domain: `play.hadaria.fr` using MCC.
3. Get the error

### Attach screenshot here (If applicable)

![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/73879444/3d001522-5593-4015-95fc-20eab3f8742b)

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

91.121.48.210

**Comment by ymonnet** [comment]
up, same issue

**Comment by milutinke** [comment]
Use Microsoft login method, Mojang login in legacy and will be disabled soon.

**Comment by erouins** [comment]
My bad, we Are using the Microsoft login method

**Comment by evilryan** [comment]
**Prerequisites**
🗸 I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
🗸 I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
🗸 I have set debugmessages=true in config to diagnose my issue
🗸 I have redacted session tokens and passwords before attaching screenshots

**Minecraft Version**
1.20.2 <-- server version

**Console Client Version**
20231125-235

**Expected Behavior**
I should be able to log into the server.

**Actual Behavior**
I have verified by logging manually into Vanilla Minecraft Launcher, as well as setting login type to "browser" in the mccclient.ini to confirm the username/password are correct and I can log in successfully to Microsoft. However, the MCC is unable to log into the server.

**Attach screenshot here (If applicable)**

![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/3334131/f5914c3f-1b13-45c2-9720-f091c1cf43c0)

**Anythings that could help diagnosing the bug**
```
Minecraft Console Client v1.20.1 - for MC 1.4.6 to 1.20.1 - Github.com/MCCTeam
GitHub build 235, built on 2023-11-25 from commit c6da4e2
Resolving catscraft.net...
Resolving catscraft.net...
Connecting to Microsoft...
Your browser should open automatically. If not, open the link below in your browser.

https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize?client_id=REDACTED&response_type=code&redirect_uri=https%3A%2F%2Fmccteam.github.io%2Fredirect.html&scope=XboxLive.signin%20offline_access%20openid%20email&prompt=select_account&response_mode=fragment

Paste your code here:
Connecting to Microsoft...
Using Minecraft version 1.20.1 (protocol v763)
[MCC] Version is supported.
Logging in...
[MCC] Checking Session...
[MCC] Login failed :
[MCC] Failed to check session.
[ERROR] Failed to login to this server.
Initialization failed.

Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
   at MinecraftClient.McClient..ctor(SessionToken session, PlayerKeyPair playerKeyPair, String server_ip, UInt16 port, Int32 protocolversion, ForgeInfo forgeInfo)
   at MinecraftClient.Program.InitializeClient()
>

```
**Device**
Desktop

**Operating System**
Windows 11 x64

**Server Address (If applicable)**
catscraft.net

**Comment by milutinke** [comment]
The Authentication system changed, try the latest version of the client.
