### ISSUE TITLE
[Question] System.Collections.Generic.KeyNotFoundException: Packet ID of 0x9D doesn't exist!

### ISSUE THREAD

**Issue by disymayufei** [MCCTeam/Minecraft-Console-Client#2569]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.1

### Console Client Version

Latest

### Expected Behavior

I expect is to be able to connect to the server normally

### Actual Behavior

The mcc warn：
Unhandled exception. System.Collections.Generic.KeyNotFoundException: Packet ID of 0x9D doesn't exist!
   at MinecraftClient.Protocol.Handlers.PacketPalettes.PacketTypePalette.GetIncommingTypeById(Int32 packetId)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

and then automatically exited.

### Steps to Reproduce the bug

1. Start MCC
2. Connect to a 1.20 Minecraft server with velocity
3. The bug happened

### Anythings that could help diagnosing the bug

```txt
> Unhandled exception. System.Collections.Generic.KeyNotFoundException: Packet ID of 0x9D doesn't exist!
   at MinecraftClient.Protocol.Handlers.PacketPalettes.PacketTypePalette.GetIncommingTypeById(Int32 packetId)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
You are playing on a server that does not follow the protocol specification.
The MCC only supports Notchian servers 1.4.6 - 1.20.1, and Forge up to 1.17.2.

**Comment by disymayufei** [comment]
But my server is spigot 1.20.1

**Comment by milutinke** [comment]
> But my server is spigot 1.20.1

Are you running it behind some sort of proxy?

**Comment by milutinke** [comment]
Closing as stale.
