### ISSUE TITLE
[BUG] Crashing randomly

### ISSUE THREAD

**Issue by Hvipz** [MCCTeam/Minecraft-Console-Client#2600]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5-1.20

### Console Client Version

Latest

### Expected Behavior

not to crash

### Actual Behavior

crashes for no reason ,sometimes after 2 hours sometimes after 4 hours

### Steps to Reproduce the bug

1. Start
2. Wait 1-2  hours
3. Crash

### Anythings that could help diagnosing the bug

```txt
Application: MinecraftClient-20231011-230-win-x64.exe
CoreCLR Version: 7.0.1123.42427
.NET Version: 7.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Sockets.SocketException (10053): Kurulan bir bağlantı, ana makinenizdeki yazılım tarafından iptal edildi.
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.SendPacket(Int32 packetID, IEnumerable`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.SendPacket(PacketTypesOut packet, IEnumerable`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Device

VPS

### Operating System

Windows

**Comment by milutinke** [comment]
Closing as outdated.
Download the latest version of the client, as a lot has changed over the span of 3 years.
