### ISSUE TITLE
[BUG] Initialization failed.

### ISSUE THREAD

**Issue by asawski** [MCCTeam/Minecraft-Console-Client#2630]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [x] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.2

### Console Client Version

Latest

### Expected Behavior

Login to server

### Actual Behavior

Cant connect to my local hosted server. I think this is something related to 1.20.2

### Steps to Reproduce the bug

1. Try connect to the server
2. See that you cant connect

### Anythings that could help diagnosing the bug

```txt
Minecraft Console Client v1.20.2 - for MC 1.4.6 to 1.20.2 - Github.com/MCCTeam
GitHub build 238, built on 2023-12-15 from commit f6797cb
[MCC] [ScriptScheduler] Loaded task:
triggeronfirstlogin: False
 triggeronlogin: False
 triggerontime: True
 triggeroninterval: True
 timevalue: 14:00:00
 timeinterval: 53.4
 action: send /hello
[MCC] [ScriptScheduler] Loaded task:
triggeronfirstlogin: False
 triggeronlogin: True
 triggerontime: False
 triggeroninterval: False
 timevalue: 
 timeinterval: 56
 action: send /login pass
[SessionCache] Initializing FileSystemWatcher for file: /home/asa/Downloads/SessionCache.ini
No sessions could be loaded from disk
Login :
Password(invisible): 
You chose to run in offline mode.
Success. (session ID: )
Server IP : 
Retrieving Server Info...
Server version : 1.20.2 (protocol v764)
[MCC] Version is supported.
Logging in...
[DEBUG] Crypto keys & hash generated.
[MCC] Checking Session...
Performing request to sessionserver.mojang.com
> POST /session/minecraft/join HTTP/1.1
> Host: sessionserver.mojang.com
> User-Agent: MCC/1.20.2
> Content-Type: application/json
> Content-Length: 95
> Connection: close
> 
> {"accessToken":"","selectedProfile":"0","serverId":"-273084d304495a34669cd084d0286ff98e1b1535"}

< HTTP/1.1 403 Forbidden
< Date: Fri, 15 Dec 2023 15:04:55 GMT
< Content-Type: application/json
< Content-Length: 83
< Connection: close
< x-minecraft-request-id: 34aa18088c59291b
< Cache-Control: no-store
< x-azure-ref: 20231215T150455Z-b62bc78h3p5sv2gwbkpqrg9mng00000002hg000000008gug
< X-Cache: TCP_MISS
< 
< {
<   "error" : "ForbiddenOperationException",
<   "path" : "/session/minecraft/join"
< }
[MCC] Login failed :
[MCC] Failed to check session.
[ERROR] Failed to login to this server.

Initialization failed.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
   at MinecraftClient.McClient..ctor(SessionToken session, PlayerKeyPair playerKeyPair, String server_ip, UInt16 port, Int32 protocolversion, ForgeInfo forgeInfo)
   at MinecraftClient.Program.InitializeClient()
```

### Device

Laptop

### Operating System

Linux

**Comment by PackmanDude** [comment]
any update?

**Comment by breadbyte** [comment]
You are running in offline mode, but the server is in online mode (i.e. requires a microsoft account.)
