### ISSUE TITLE
[BUG] Crash after join the server

### ISSUE THREAD

**Issue by oldkingOK** [MCCTeam/Minecraft-Console-Client#2652]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.1 Forge 47.2.19

### Console Client Version

20240114-240

### Expected Behavior

Able to connect to the server and send messages normally

### Actual Behavior

After the `Type '/quit' to leave the server.` output, the client crashes with InvalidDataException

### Steps to Reproduce the bug

1. Download [Forge server starter](https://www.curseforge.com/minecraft/mc-mods/forge-server-starter/download)
2. Install 1.20.1 with forge version 47.2.19
3. Start the server and connect it with a client

### Anythings that could help diagnosing the bug

Log from client

```txt

Received FML3 Server Mod Data List
Received FML2 Server Mod List
Sending back FML2 Client Mod List
Acknowledging FML2 Server Registry: minecraft:command_argument_type
Acknowledging FML2 Server Registry: minecraft:recipe_serializer
{"enforcesSecureChat":true,"forgeData":{"channels":[],"mods":[],"truncated":false,"fmlNetworkVersion":3,"d":"^\u0000\u0000ࠄ㐤獋㙖⹌ᦘ̺⸱恤䒸⡑⛧沮婙㨹牥ఈㄵচ₀沮婙㨹牥ఈㄵচ偀泀岛㊳䄃㊜倱⭋眦湫Მ㒺杮戆䂸⠁ܰⶎ崚ᢁㄮ\u0002"},"description":{"text":"A Minecraft Server"},"players":{"max":20,"online":0},"version":{"name":"1.20.1","protocol":763}}
Server is running Forge with 2 mods.
Mod list:
  minecraft v1.20.1
  forge vANY
Server version : 1.20.1 (protocol v763, with Forge)
Acknowledging FML2 Server Registry: minecraft:sound_event
Acknowledging FML2 Server Registry: minecraft:particle_type
Acknowledging FML2 Server Registry: minecraft:villager_profession
Acknowledging FML2 Server Registry: minecraft:item
Acknowledging FML2 Server Registry: minecraft:potion
Acknowledging FML2 Server Registry: minecraft:painting_variant
Acknowledging FML2 Server Registry: forge:fluid_type
Acknowledging FML2 Server Registry: minecraft:block_entity_type
Acknowledging FML2 Server Registry: forge:display_contexts
Acknowledging FML2 Server Registry: minecraft:block
Acknowledging FML2 Server Registry: forge:entity_data_serializers
Acknowledging FML2 Server Registry: minecraft:mob_effect
Acknowledging FML2 Server Registry: minecraft:stat_type
Acknowledging FML2 Server Registry: minecraft:menu
Acknowledging FML2 Server Registry: minecraft:enchantment
Acknowledging FML2 Server Registry: minecraft:fluid
Acknowledging FML2 Server Registry: minecraft:entity_type
Acknowledging FML2 Server Config: forge-server.toml
[MCC] Server was successfully joined.
Type '/quit' to leave the server.
[DEBUG] Receive JoinGame
[DEBUG] CanSendMessage = False
[DEBUG] SendPlayerSession MessageUUID = 0872c31f-c03e-4387-a54a-4c311a665a7b,  len(PublicKey) = 294, len(SignatureV2) = 1
[DEBUG] Receive DeclareCommands
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type DeclareCommands. (PacketID: 16, Protocol: 763, LoginPhase: False, InnerException: System.IndexOutOfRangeException).
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MinecraftClient.Protocol.Handlers.packet.s2c.DeclareCommands.ExtractRootCommand()
   at MinecraftClient.Protocol.Handlers.packet.s2c.DeclareCommands.Read(DataTypes dataTypes, Queue`1 packetData, Int32 protocolVersion)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePlayPackets(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted
```

Log from Server

```
[11:44:23] [User Authenticator #1/INFO] [minecraft/ServerLoginPacketListenerImpl]: UUID of player oldkingOK is *
[11:44:24] [Netty Server IO #12/ERROR] [ne.mi.ne.si.IndexedMessageCodec/SIMPLENET]: Received empty payload on channel fml:handshake
[11:44:25] [Server thread/INFO] [minecraft/PlayerList]: oldkingOK[/127.0.0.1:60418] logged in with entity id 227 at (-37.5, 60.0, 71.5)
[11:44:26] [Server thread/INFO] [minecraft/MinecraftServer]: oldkingOK joined the game
[11:44:27] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: QQbot lost connection: Disconnected
[11:44:27] [Server thread/INFO] [minecraft/MinecraftServer]: oldkingOK left the game
```

### Device

Desktop

### Operating System

Linux

**Comment by oldkingOK** [comment]
I read the wiki and found that Forge added two Parsers to Command Data, `forge:modid` and `forge:enum`.
And forge-enum has a string type Properties, forge-modid has no Properties

> Reference: https://wiki.vg/Command_Data#Parsers

So I tried adding a ForgeEnumParser to `MinecraftClient/Protocol/Handlers/Packet/s2c/DeclareCommands.cs` and `ReadNextString()` when Varint Id is 51. (I've tried 50,51 and 52 and it only works at 51 and prints the class name of the Forge Enum. The commit is [here](https://github.com/MCCTeam/Minecraft-Console-Client/compare/master...oldkingOK:Minecraft-Console-Client:forge-cmds))

It still needs more tests.

**Comment by freeze-dolphin** [comment]
I'm encountering the same problem, with the latest release version MCC, on my 1.19.2 forge server.

```
Minecraft Console Client v1.20.4 - for MC 1.4.6 to 1.20.4 - Github.com/MCCTeam
GitHub build 276, built on 2024-09-06 from commit 27e6643
You chose to run in offline mode.
Using Minecraft version 1.19.2 (protocol v760)
Force-enabling Forge support.
[MCC] Version is supported.
Logging in...
[MCC] Server is in offline mode.
[MCC] Server was successfully joined.
Type '/quit' to leave the server.
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type DeclareCommands. (PacketID: 15, Protocol: 760, LoginPhase: False, InnerException: System.InvalidOperationException).
 ---> System.InvalidOperationException: Queue empty.
   at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
   at System.Collections.Generic.Queue`1.Dequeue()
   at MinecraftClient.Protocol.Handlers.packet.s2c.DeclareCommands.Read(DataTypes dataTypes, Queue`1 packetData, Int32 protocolVersion) in /home/runner/work/Minecraft-Console-Client/Minecraft-Console-Client/MinecraftClient/Protocol/Handlers/Packet/s2c/DeclareCommands.cs:line 26
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePlayPackets(Int32 packetId, Queue`1 packetData) in /home/runner/work/Minecraft-Console-Client/Minecraft-Console-Client/MinecraftClient/Protocol/Handlers/Protocol18.cs:line 744
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData) in /home/runner/work/Minecraft-Console-Client/Minecraft-Console-Client/MinecraftClient/Protocol/Handlers/Protocol18.cs:line 376
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData) in /home/runner/work/Minecraft-Console-Client/Minecraft-Console-Client/MinecraftClient/Protocol/Handlers/Protocol18.cs:line 376
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o) in /home/runner/work/Minecraft-Console-Client/Minecraft-Console-Client/MinecraftClient/Protocol/Handlers/Protocol18.cs:line 259
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted

```
