### ISSUE TITLE
[BUG] Can't use Command-line settings

### ISSUE THREAD

**Issue by italoseara** [MCCTeam/Minecraft-Console-Client#2685]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.4

### Console Client Version

9a147b5

### Expected Behavior

Debug messages to be turned on

### Actual Behavior

When i run `./MinecraftClient --debugmessages=false` on linux, it shows this error message:

```
Minecraft Console Client v1.20.2 - for MC 1.4.6 to 1.20.2 - Github.com/MCCTeam
GitHub build 247, built on 2024-02-18 from commit 9a147b5
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at MinecraftClient.Settings.LoadArguments(String[] args)
   at MinecraftClient.Program.Main(String[] args)
[1]    35941 IOT instruction (core dumped)  ./MinecraftClient --debugmessages=false
➜  MinecraftCLI
```

### Steps to Reproduce the bug

1. run `./MinecraftClient --debugmessages=false`

### Attach screenshot here (If applicable)

![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/54297273/26df9636-cade-4431-8421-7ae743c449a6)

### Anythings that could help diagnosing the bug

```txt
I know i can just turn debug messages on in the configuration file, but my goal is to run it from anywhere in my pc without creating configuration files on everywhere i use it, maybe using `--sessioncache="memory"` but the same error occours.
```

### Device

Desktop

### Operating System

Linux

**Comment by oldkingOK** [comment]
I have a same issue with ubuntu in termux.

**Comment by milutinke** [comment]
@oldkingOK Fixed. Use the latest release.
