### ISSUE TITLE
[BUG] Logs in to server and gets logged out due to can't process JoinGame packet correctly

### ISSUE THREAD

**Issue by BurkenDev** [MCCTeam/Minecraft-Console-Client#2741]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.6 / 1.20.4 / 1.21

### Console Client Version

Latest

### Expected Behavior

Logged in correctly

### Actual Behavior

Logging in, you see the new character enter the game, 0.5 seconds later quits with this message:

> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type JoinGame. (PacketID: 40, Protocol: 763, LoginPhase: False, InnerException: System.Collections.Generic.KeyNotFoundException).
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'minecraft:chat_type' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MinecraftClient.Protocol.Message.ChatParser.ReadChatType(Dictionary`2 registryCodec)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePlayPackets(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted

### Steps to Reproduce the bug

1. login to a server using the client

### Device

Other

### Operating System

Linux

**Comment by breadbyte** [comment]
1.20.4+ is not fully supported yet. There has been some work in progress but no ETA as of the moment since there are major changes and additions to the minecraft protocol.

**Comment by milutinke** [comment]
> 1.20.4+ is not fully supported yet. There has been some work in progress but no ETA as of the moment since there are major changes and additions to the minecraft protocol.

1.20.4 is supported, 1.20.6 is not yet supported.

@BurkenDev This is a problem with the server using a chat plugin that modifies the chat and sends a different non-vanilla chat structure and format, thus the MCC crashes because it only processes a vanilla packets.

If it's your server, get rid of the chat plugins, if it's not you'll have to download the code of the client, change a method and re-compile it.
In `ChatParser.cs`, replace the `ParseText` method with the following code:

```csharp
public static string ParseText(string json, List<string>? links = null)
{
  var isJson = false;
            
  try
  {
    isJson = JsonDocument.Parse(json) != null;
  }
  catch
  {
    isJson = false;
  }

  return !isJson ? json : JSONData2String(Json.ParseJson(json), "", links);
}
```
Follow the instructions on how to build/compile the project from the source code here: https://mccteam.github.io/guide/installation.html#building-from-the-source-code

**Comment by milutinke** [comment]
I don't consider this as a bug, because it's not vanilla behavior and I only heard of 2 people having this issue.
