### ISSUE TITLE
[BUG] cannot join the game

### ISSUE THREAD

**Issue by xiaodangya** [MCCTeam/Minecraft-Console-Client#2767]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20

### Console Client Version

272

### Expected Behavior

repair it

### Actual Behavior

can't joined the other game in server

### Steps to Reproduce the bug

1. joined the server
2. join the other world
3. 
4. 
5. 

### Anythings that could help diagnosing the bug

```txt
[DEBUG] SendPlayerSession MessageUUID = 34638e4a-2818-4a5e-82bd-2c963deb39b9,  len(PublicKey) = 294, len(SignatureV2) = 512
> Unhandled exception. System.IO.InvalidDataException: 无法处理传入的JoinGame类型的数据包。(数据包ID：40，协议：763，登 陆阶段：False，内部异常：System.Collections.Generic.KeyNotFoundException)。
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'minecraft:chat_type' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MinecraftClient.Protocol.Message.ChatParser.ReadChatType(Dictionary`2 registryCodec)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePlayPackets(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

play.moonmc.cn

**Comment by lkctrl** [comment]
i have same problem with you when join a 1.21 server using 1.20.1(server have viaversion and can join with a normal 1.20.1minecraftclient)
and i have no idea how to resolve that
waiting for issue...

**Comment by milutinke** [comment]
We now properly support all versions from 1.20 to 26.1, this should be fixed.
If you experience it again for some reason, re-open the issue.
