### ISSUE TITLE
[BUG] Can't join game crashes out

### ISSUE THREAD

**Issue by BurkenDev** [MCCTeam/Minecraft-Console-Client#2774]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.21

### Console Client Version

20240713-273

### Expected Behavior

Join and stay online and not crash out 1 second after joining the server??

### Actual Behavior

> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type JoinGame. (PacketID: 40, Protocol: 763, LoginPhase: False, InnerException: System.Collections.Generic.KeyNotFoundException).
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'minecraft:chat_type' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MinecraftClient.Protocol.Message.ChatParser.ReadChatType(Dictionary`2 registryCodec)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePlayPackets(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted

### Steps to Reproduce the bug

# ./MinecraftClient-20240713-273-linux-x64

### Device

Other

### Operating System

Linux

**Comment by milutinke** [comment]
1.21 is not supported yet.
It will be when I have the time to finish 1.20.6 (porting it to 1.21 will be quick).

**Comment by milutinke** [comment]
Closing as resolved, as we support every version from 1.4 to 26.1
