### ISSUE TITLE
[BUG] cant join cosmicreborn.com

### ISSUE THREAD

**Issue by Snippy420** [MCCTeam/Minecraft-Console-Client#2806]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.7.10

### Console Client Version

Lastest

### Expected Behavior

joins the server

### Actual Behavior

closes the console

### Steps to Reproduce the bug

1. join cosmicreborn.com on 1.7.10
2. 
3. 

### Anythings that could help diagnosing the bug

```txt
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type ScoreboardObjective. (PacketID: 59, Protocol: 5, LoginPhase: False, InnerException: System.InvalidOperationException).
 ---> System.InvalidOperationException: Queue empty.
   at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
   at System.Collections.Generic.Queue`1.Dequeue()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePlayPackets(Int32 packetId, Queue`1 packetData) in /home/runner/work/Minecraft-Console-Client/Minecraft-Console-Client/MinecraftClient/Protocol/Handlers/Protocol18.cs:line 2576
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData) in /home/runner/work/Minecraft-Console-Client/Minecraft-Console-Client/MinecraftClient/Protocol/Handlers/Protocol18.cs:line 495
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData) in /home/runner/work/Minecraft-Console-Client/Minecraft-Console-Client/MinecraftClient/Protocol/Handlers/Protocol18.cs:line 495
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o) in /home/runner/work/Minecraft-Console-Client/Minecraft-Console-Client/MinecraftClient/Protocol/Handlers/Protocol18.cs:line 259
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()
```

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

cosmicreborn.com

**Comment by milutinke** [comment]
Fixed in #3033
